version: "3"

services:
  app-murilo:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: murilo-be
    ports:
      - "8014:80"
    volumes:
      - .:/var/www/html
